version: "3.8"

services:
  mysql:
    container_name: lend_qr_mysql
    image: mysql:latest
    restart: always
    volumes:
      - lend_qr_db_data:/var/lib/mysql
    ports:
      - "6710:3306"
    environment:
      MYSQL_DATABASE: lend_qr_db
      MYSQL_USER: lend_qr_db
      MYSQL_PASSWORD: u1wVreGixnrQsVFVq4GF
      MYSQL_ROOT_PASSWORD: rootpassword # Change this to a secure password

  app:
    build: .
    container_name: lend_qr_app
    ports:
      - "6711:3000"
      - "9229:9229"
    environment:
      APP_NAME: lend_qr
      PORT: 3000
      NODE_ENV: development
      DEBUG: express:*
      DATABASE_URL: mysql://lend_qr_db:u1wVreGixnrQsVFVq4GF@mysql:3306/lend_qr_db

    command: >
      bash -c "npx prisma migrate deploy && nodemon src/server.ts"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  lend_qr_db_data:
