/**
 * Express router paths go here.
 */

// /api/user/profile/{userId}
export default {
  Base: "/api",
  Version1: "/v1",
  Users: {
    Base: "/users",
    CheckUserNameAvailability: "/check-username",
    AllInterests: "/interests/all",
    UserInterests: "/interests",
    SelectUserAvatar: "/select-avatar/:userId",
    GetUnattachedAvatars: "/avatars",
    UploadUnattachedAvatar: "/avatar",
    SelectUserStructure: "/select-structure/:userId",
    GetUnattachedStructures: "/structures",
    UploadUnattachedStructure: "/structure",
    createHighlight: "/highlights/:userId",
    registerUser: "/register",
    loginUser: "/login",
    loginPartner: "/login/partner",
    setLocation: "/set-location",
    updateUserName: "/username/:userId",
    getStoreFront: "/storefront/:storeId",

    Profile: {
      Base: "/profile/:userId",
      Edit: "/profile"
    },
    Search: {
      Base: "/search",
      DeepSearch: "/general",
    },
    GeneralSettings: "/settings/general/:userId",
    ActivateAccount: "/account-verification",
    ResetPasswordRequest: "/forgot-password",
    VerifyResetPasswordToken: "/forgot-password/otp",
    SetNewPassword: "/reset-password",
    ToggleFollow: "/follow/:userId",
    GetFollowers: "/followers/:userId",
    GetFollowing: "/following/:userId",
    GetReps: "/:userId/representation",
    GetNearbyUsersReps: "/nearby",
  },
  UserEnum: {
    Base: "/enum",
    UserClass: "/user-class",
  },
  Thread: {
    Base: "/threads",
    default: "/",
    getSingleThread: "/:threadId/comments",
    likeThread: "/:threadId/like",
    deleteThread: "/:threadId",
    getUserThread: "/:userId",
    postComments: "/:threadId/comments",
  },
  Reports: {
    Base: "/reports",
    GetReports: "/all/reported",
    GetCases: "/all/cases-against",
    GetSingleReport: "/:reportId",
    CreateReport: "/new/:userId",
    EditReport: "/edit/:reportId",
    deleteReport: "/delete/:reportId",
    AssignReviewer: "/assign/:reportId?",
    StartReview: "/start-review/:reportId?",
    FinalizeReview: "/end-review/:reportId?",
  },

  storefront: {
    Base: "/storefront",
    getItemsInStorefrontControllerOwner: "/:storeId/items/:itemId/owner",
    getItemsInStoreFront: "/:storeId/items",
    getCollectionsInStorefront: "/:storeId/collections",
    getCategoriesInStorefront: "/:storeId/categories",
    createNewCategoryInStoreFront: "/:storeId/categories",
    createNewCollectionInStorefront: "/:storeId/collection",
    createItem: "/:storeId/items",
    getStorefrontdetailsOwner: "/:storeId/owner",
    performActionOnStorefront: "/:storeId/items/:itemId/action",
    searchItemsInStorefront: "/:storeId/items",
    getStoreFront: "/:storeId",
  },
  Chats: {
    Base: "/chats",
    AllChats: "/",
    SearchDirectMessage: "/search/:chatId?",
    // SearchMessages: "/search",
    SendDirectMessage: "/send/:userId?",
    RetreiveDirectMessage: "retreive/:chatId",
    UpdateMessageStatus: "/status-update/:chatId",
  },
  Auth: {
    Base: "/auth",
    Registration: "/register",
    Login: "/login",
    loginPartner: "/login/partner",
    ValidateRequest: "/miniapp/validate-request",
    GetUserAuthorization: "/miniapp/user-authorization",
    GetAuthorizationToken: "/miniapp/fetch-token",
    ActivateAccount: "/account-verification",
    ResetPasswordRequest: "/forgot-password",
    VerifyResetPasswordToken: "/forgot-password/otp",
    SetNewPassword: "/reset-password",
  },
  Statistics: {
    Base: "/statistics",
    GetTrendingTags: "/tags/trending/top",
    GetActiveTrendingTags: "/tags/trending/latest",
    GetViralTags: "/tags/viral/top",
    GetActiveViralTags: "/tags/viral/latest",
    GetUsersActiveHours: "/users/active-hours",
    GetUsersAvgTimeSpent: "/users/avg-time-spent",
    GetUsersLocation: "/users/location/top",
    GetUsersSearchHistory: "/users/searches/top",
    GetUsersActiveSearchHistory: "/users/searches/latest",
  },
  Notification: {
    Base: "/notifications",
    GetAllUnreadNotifications: "/unread",
    MarkAsViewed: "/viewed/:notificationId",
  },
  MiniApp: {
    Base: "/miniapp",
    GetAll: "/",
    RetrieveApp: "/:appId",
    UpdateApp: "/:appId/description",
    DeleteApp: "/:appId",
    Activate: "/activate",
    Deactivate: "/deactivate",
  },
  Dashboard: {
    Base: "/dashboard",
    ProfileInsights: "/profile-insights",
  },
} as const;
